include:
  - project: DIT/REPO
    ref: main
    file: express.yml

workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      variables:
        URL: 'https://api.tlaxcala.gob.mx/eventos'
        EPORT: '8011'
        ENV: |
          MONGO_URL=$MONGO_URL
          SECRET_COOKIE=$SECRET_COOKIE
          JWT_KEY=$JWT_KEY
          EMISOR_JWT=$EMISOR_JWT
          CORREO_PASSWORD=$CORREO_PASSWORD
        MOUNTS: |
          - "~/vols/$CI_PROJECT_NAME/logs:/usr/src/logs:z"
          - "~/vols/$CI_PROJECT_NAME/uploads:/usr/src/uploads:z"
    - if: '$CI_COMMIT_BRANCH == "stg"'
      variables:
        EPORT: '13011'
        ENV: |
          MONGO_URL=$MONGO_URL_DEV
          SECRET_COOKIE=$SECRET_COOKIE
          JWT_KEY=$JWT_KEY
          EMISOR_JWT=$EMISOR_JWT
          CORREO_PASSWORD=$CORREO_PASSWORD
        MOUNTS: |
          - "~/vols/$CI_PROJECT_NAME/logs:/usr/src/logs:z"
          - "~/vols/$CI_PROJECT_NAME/uploads:/usr/src/uploads:z"
    - when: never
