pipeline{
    agent any
    options {
        timeout(time:10, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '5', artifactNumToKeepStr: '5'))
    }
    environment {
        REGISTRY = 'registry.tlaxcala.gob.mx/ddt/credencializacion-des'
        USER = 'gitlab-ci-token'
        SERVER_IP = '10.50.230.120'
        SERVER_IP_DEV = '10.50.230.95'
        SERVER_USER = 'deployer'
        TAG = sh(returnStdout: true, script: "git rev-parse --short=10 HEAD").trim()
    }
    stages{
        stage('Pull changes'){
            steps{
                script{
                    sh 'git pull origin ${BRANCH_NAME}'
                }
            }
        }
        stage('Push Docker image'){
            steps{
                script{
                    withCredentials([string(credentialsId: 'access-token-credencializacion-des', variable: 'ACCESS_TOKEN')]){
                        if(env.BRANCH_NAME == 'stg'){
                            sh 'docker build -f dev.Dockerfile -t $REGISTRY:$TAG -t $REGISTRY:stg-latest .'
                            sh 'echo $ACCESS_TOKEN | docker login -u ${USER} --password-stdin $REGISTRY'
                            sh 'docker push $REGISTRY:$TAG'
                            sh 'docker push $REGISTRY:stg-latest'
                            sh 'docker logout $REGISTRY'
                        }
                        if(env.BRANCH_NAME == 'main'){
                            sh 'docker build -f prod.Dockerfile -t $REGISTRY:$TAG -t $REGISTRY:latest .'
                            sh 'echo $ACCESS_TOKEN | docker login -u ${USER} --password-stdin $REGISTRY'
                            sh 'docker push $REGISTRY:$TAG'
                            sh 'docker push $REGISTRY:latest'
                            sh 'docker logout $REGISTRY'
                        }
                    }
                }
            }
        }
        stage('Runing Docker image'){
            steps{
                script{
                    if(env.BRANCH_NAME == 'stg'){
                        withCredentials([
                            sshUserPrivateKey(credentialsId: 'ssh-key-deployer-dev', keyFileVariable: 'keyfile'),
                            string(credentialsId: 'access-token-credencializacion-des', variable: 'ACCESS_TOKEN'),
                            string(credentialsId: 'mongo-url-pub-dev', variable: 'MONGO_URL'),
                            string(credentialsId: 'jwt-key-credencializacion-des', variable: 'JWT_KEY'),
                            string(credentialsId: 'secret-cookie-credencializacion-des', variable: 'SECRET_COOKIE'),
                            string(credentialsId: 'jwt-emisor-credencializacion-des', variable: 'EMISOR_JWT'),
                            string(credentialsId: 'contrasena-correo-noreply', variable: 'CORREO_PASSWORD')
                        ]){
                            sh 'ssh -i ${keyfile} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_DEV "echo $ACCESS_TOKEN | docker login -u ${USER} --password-stdin $REGISTRY"'
                            sh 'ssh -i ${keyfile} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_DEV "docker pull $REGISTRY:stg-latest"'
                            sh 'ssh -i ${keyfile} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_DEV "docker rm -f node-express-pub | true"'
                            sh """
                                ssh -i ${keyfile} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_DEV "docker run -d -p 9008:3000 \
                                    --mount type=bind,source=/home/omg/app_gob_pub/credencializacion-des/app/logs,target=/usr/src/app/logs \
                                    --mount type=bind,source=/home/omg/app_gob_pub/credencializacion-des/app/uploads/adjuntos,target=/usr/src/app/uploads/adjuntos \
                                    --mount type=bind,source=/home/omg/app_gob_pub/credencializacion-des/app/uploads/evidencias,target=/usr/src/app/uploads/evidencias \
                                    --env MONGO_URL='${MONGO_URL}' \
                                    --env JWT_KEY='${JWT_KEY}' \
                                    --env SECRET_COOKIE='${SECRET_COOKIE}' \
                                    --env EMISOR_JWT='${EMISOR_JWT}' \
                                    --env CORREO_PASSWORD='${CORREO_PASSWORD}' \
                                    --env NODE_ENV='stg' \
                                    --restart always \
                                    --name node-express-pub $REGISTRY:stg-latest"
                            """
                            sh 'ssh -i ${keyfile} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP_DEV "docker logout $REGISTRY"'
                        }
                    }
                    if(env.BRANCH_NAME == 'main'){
                        withCredentials([
                            sshUserPrivateKey(credentialsId: 'ssh-key-deployer-back', keyFileVariable: 'keyfile'),
                            string(credentialsId: 'access-token-credencializacion-des', variable: 'ACCESS_TOKEN'),
                            string(credentialsId: 'mongo-url-pub-dev', variable: 'MONGO_URL'),
                            string(credentialsId: 'jwt-key-credencializacion-des', variable: 'JWT_KEY'),
                            string(credentialsId: 'secret-cookie-credencializacion-des', variable: 'SECRET_COOKIE'),
                            string(credentialsId: 'jwt-emisor-credencializacion-des', variable: 'EMISOR_JWT'),
                            string(credentialsId: 'contrasena-correo-noreply', variable: 'CORREO_PASSWORD')
                        ]){
                            sh 'ssh -i ${keyfile} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "echo $ACCESS_TOKEN | docker login -u ${USER} --password-stdin $REGISTRY"'
                            sh 'ssh -i ${keyfile} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker pull $REGISTRY"'
                            sh 'ssh -i ${keyfile} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker rm -f node-express-credencializacion-des | true"'
                            sh """
                                ssh -i ${keyfile} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker run -d -p 9008:3000 \
                                    --mount type=bind,source=/home/tohui/credencializacion-des/app/logs,target=/usr/src/app/logs \
                                    --mount type=bind,source=/home/tohui/credencializacion-des/app/uploads/adjuntos,target=/usr/src/app/uploads/adjuntos \
                                    --mount type=bind,source=/home/tohui/credencializacion-des/app/uploads/evidencias,target=/usr/src/app/uploads/evidencias \
                                    --env MONGO_URL='${MONGO_URL}' \
                                    --env JWT_KEY='${JWT_KEY}' \
                                    --env SECRET_COOKIE='${SECRET_COOKIE}' \
                                    --env EMISOR_JWT='${EMISOR_JWT}' \
                                    --env CORREO_PASSWORD='${CORREO_PASSWORD}' \
                                    --restart always \
                                    --name node-express-credencializacion-des $REGISTRY"
                            """
                            sh 'ssh -i ${keyfile} -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "docker logout $REGISTRY"'
                        }
                    }
                }
            }
        }
    }
}
